builds:
  - id: smtp_to_telegram
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - '7'
    binary: smtp_to_telegram
    tags:
      - urfave_cli_no_docs

dockers:
  - image_templates:
      - 'simplylizz/smtp_to_telegram:{{ .Tag }}-amd64'
    use: buildx
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"

  - image_templates:
      - 'simplylizz/smtp_to_telegram:{{ .Tag }}-arm64'
    use: buildx
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64/v8"

  - image_templates:
      - 'simplylizz/smtp_to_telegram:{{ .Tag }}-armv7'
    use: buildx
    dockerfile: Dockerfile.release
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm/v7"

docker_manifests:
  - name_template: 'simplylizz/smtp_to_telegram:{{ .Tag }}'
    image_templates:
    - 'simplylizz/smtp_to_telegram:{{ .Tag }}-amd64'
    - 'simplylizz/smtp_to_telegram:{{ .Tag }}-arm64'
    - 'simplylizz/smtp_to_telegram:{{ .Tag }}-armv7'
  - name_template: 'simplylizz/smtp_to_telegram:latest'
    image_templates:
      - 'simplylizz/smtp_to_telegram:{{ .Tag }}-amd64'
      - 'simplylizz/smtp_to_telegram:{{ .Tag }}-arm64'
      - 'simplylizz/smtp_to_telegram:{{ .Tag }}-armv7'