name: Docker (Build)

# Controls when the workflow will run
on:
  push:
    branches:
      - '*'
    paths:
      - 'Dockerfile'   
  pull_request:
    branches:
      - '*'
    paths:
      - 'Dockerfile'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - uses: actions/checkout@v4
      # https://github.com/docker/setup-qemu-action
      - uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/muratovas/smtptg
          # Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
